services:
  mysql:
    image: mysql:8.0
    container_name: xk-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xk_truck_dev
      TZ: Asia/Taipei
    ports:
      - "3306:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
      --default-time-zone=+08:00
    volumes:
      - ./mysql-data:/var/lib/mysql
