spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xk_truck_dev?useSSL=false&serverTimezone=Asia/Taipei&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1qaz@WSX}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update       # 開發期方便；正式環境請改用 Flyway
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Taipei
        # MySQL 8 可不指定 dialect，若要固定：
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    time-zone: Asia/Taipei

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace   # 顯示綁定參數(開發期用)
